### ISSUE TITLE
On my box Clojure beats out F#

### ISSUE THREAD

**Issue by didibus** [c-cube/hashset_benchs#1]
Here's the Clojure version:

```
(ns hash-set-bench
  (:import [java.util HashSet]))

(set! *unchecked-math* true)

(deftype Point [^long i ^long j]
  Object
  (equals [this that] (and (= (.i this) (.i ^Point that))
                           (= (.j this) (.j ^Point that))))
  (hashCode [this] (+ (.i this) (* 4000 (.j this)))))

(defn iter-neighbors [f ^Point p]
  (let [i ^long (.i p)
        j ^long (.j p)]
    (f (Point. (dec i) j))
    (f (Point. (inc i) j))
    (f (Point. i (dec j)))
    (f (Point. i (inc j)))))

(defn nth* [^long n p]
  (loop [n n
         s1 (HashSet. [p])
         s2 (HashSet.)]
    (if (zero? n)
      s1
      (let [s0 (HashSet.)]
        (letfn [(add [p]
                     (when (not (or (.contains s1 p) (.contains s2 p)))
                       (.add s0 p)))]
               (doseq [p s1] (iter-neighbors add p))
               (recur (dec n) s0 s1))))))

(printf "result is %d" (count (nth* 2000 (Point. 0 0))))
```

**Runs in 2.043087 sec
While F# runs in 2.325822 sec**

And here's an even faster Clojure version (which is less similar to the F# implementation), which runs in only 1.354060 sec:

```
(ns hash-set-bench
  (:import [java.util HashSet]))

(set! *unchecked-math* true)

(deftype point-fast [^long i ^long j]
  Object
  (equals [this that] (and (= (.i this) (.i ^point-fast that))
                           (= (.j this) (.j ^point-fast that))))
  (hashCode [this] (+ (.i this) (* 4000 (.j this)))))

(defn iter-neighbors-fast [f ^point-fast p]
  (let [i ^long (.i p)
        j ^long (.j p)]
    (f (point-fast. (dec i) j))
    (f (point-fast. (inc i) j))
    (f (point-fast. i (dec j)))
    (f (point-fast. i (inc j)))))

(defn nth-fast [^long n p]
  (loop [n n
         s1 (doto (HashSet.) (.add p))
         s2 (HashSet.)]
    (if (zero? n)
      s1
      (let [s0 (HashSet. (* 4 (.size s1)))
            it (.iterator s1)]
        (letfn [(add [p]
                     (when (not (or (.contains s1 p) (.contains s2 p)))
                       (.add s0 p)))]
               (dotimes [_ (.size s1)] (iter-neighbors-fast add (.next it))))
        (recur (dec n) s0 s1)))))
```

Maybe you could add them to the benchmarks?

**Comment by c-cube** [comment]
Fyi, I get those results on my machine @ work (I suppose the F# version I got is slow for some reason?):

> === F#
result is 8000
1.95user 0.08system 0:02.03elapsed 100%CPU (0avgtext+0avgdata 47428maxresident)k
0inputs+0outputs (0major+92174minor)pagefaults 0swaps
=== OCaml
result is 8000
1.87user 0.00system 0:01.88elapsed 99%CPU (0avgtext+0avgdata 9048maxresident)k
0inputs+0outputs (0major+2071minor)pagefaults 0swaps
=== rust
8000
2.45user 0.00system 0:02.46elapsed 99%CPU (0avgtext+0avgdata 6812maxresident)k
0inputs+0outputs (0major+264minor)pagefaults 0swaps
=== clojure
result is 8000
2.74user 0.04system 0:01.97elapsed 140%CPU (0avgtext+0avgdata 509324maxresident)k
0inputs+0outputs (0major+10838minor)pagefaults 0swaps
=== clojure_bis
result is 8000
2.42user 0.06system 0:01.81elapsed 137%CPU (0avgtext+0avgdata 491084maxresident)k
0inputs+0outputs (0major+10922minor)pagefaults 0swaps
make  14.12s user 0.25s system 111% cpu 12.931 total

**Comment by c-cube** [comment]
Note: I don't know how to compile the clojure benchs, so the startup time is probably higher than it could.

**Comment by didibus** [comment]
It's probably startup time. Clojure has notoriously slow startup time. I was counting time without startup for both F# and Clojure by using timers within the language to count the time.
